Vagrant.configure("2") do |config|
    #docker
    config.vm.define "docker" do |docker|
        docker.vm.box = "ubuntu/focal64"
        docker.vm.synced_folder "../instaladores", "/vagrant/instaladores", disabled: false
        docker.vm.synced_folder "../ansible", "/vagrant/ansible", disabled: false
        docker.vm.synced_folder "../scripts", "/vagrant/scripts", disabled: false
        docker.vm.synced_folder "../files", "/vagrant/files", disabled: false
        docker.vm.provision "shell", inline: "curl -fsSL https://deb.nodesource.com/setup_current.x | bash -"
        docker.vm.provision "shell", inline: "chmod +x /vagrant/scripts/install_ansible.sh"
        docker.vm.provision "shell", inline: "/bin/bash /vagrant/scripts/install_ansible.sh"
        docker.vbguest.no_remote = true
        docker.vbguest.auto_update = false
        docker.vm.network "public_network", ip: "192.168.1.45"
        docker.vm.provider "virtualbox" do |v|     
            v.memory= 2048
            v.cpus = 2
            v.name = "docker"
        end
    end

    # config.vm.define "vm" do |vm|
    #     vm.vm.box = "ubuntu/focal64"
    #     vm.vm.synced_folder "../ansible", "/vagrant", disabled: false
    #     vm.vm.provision "shell", inline: "apt-get update -y"
    #     vm.vm.provision "shell", inline: "apt-get install ansible"
    #     vm.vbguest.no_remote = true
    #     vm.vbguest.auto_update = false
    #     vm.vm.network "public_network", ip: "192.168.1.46"
    #     vm.vm.provider "virtualbox" do |v|     
    #         v.memory= 2048
    #         v.cpus = 2
    #         v.name = "vm"
    #     end
    # end
end
