Vagrant.configure("2") do |config|
    #db_suitecrm
    config.vm.define "db_suitecrm" do |db_suitecrm|
        db_suitecrm.vm.box = "ubuntu/focal64"
        db_suitecrm.vbguest.no_remote = true
        db_suitecrm.vbguest.auto_update = false
        db_suitecrm.vm.network "public_network", ip: "192.168.1.40"
        db_suitecrm.vm.provider "virtualbox" do |v|     
            v.memory= 2048
            v.cpus = 2
            v.name = "db_suitecrm"
        end
    end
end
