Vagrant.configure("2") do |config|
    #db_suitecrm
    config.vm.define "db_suitecrm" do |db_suitecrm|
        db_suitecrm.vm.box = "ubuntu/focal64"
        db_suitecrm.vm.synced_folder "db_suitecrm", "/vagrant", disabled: true
        db_suitecrm.vbguest.no_remote = true
        db_suitecrm.vbguest.auto_update = false
        db_suitecrm.vm.network "public_network", bridge: "enp0s31f6", ip: "192.168.1.40"
        db_suitecrm.vm.provider "virtualbox" do |v|     
            v.memory= 2048
            v.cpus = 2
            v.name = "db_suitecrm"
        end
    end
    #app_suitecrm
    config.vm.define "app_suitecrm" do |app_suitecrm|
        app_suitecrm.vm.box = "ubuntu/focal64"
        app_suitecrm.vm.synced_folder "app_suitecrm", "/vagrant", disabled: true
        app_suitecrm.vbguest.no_remote = true
        app_suitecrm.vbguest.auto_update = false
        app_suitecrm.vm.network "public_network", bridge: "enp0s31f6", ip: "192.168.1.41"
        app_suitecrm.vm.provider "virtualbox" do |v|     
            v.memory= 2048
            v.cpus = 2
            v.name = "app_suitecrm"
        end
    end
end
