Vagrant.configure("2") do |config|
    # config.vm.synced_folder "docker/", "/vagrant", type:"virtualbox"  
    config.vm.provision "shell", inline: "curl -fsSL https://get.docker.com -o get-docker.sh"
    config.vm.provision "shell", inline: "sudo sh get-docker.sh"
    config.vm.provision "shell", inline: "sudo usermod -aG docker vagrant"
    #docker_manager
    config.vm.define "docker_manager" do |docker_manager|
        docker_manager.vm.box = "ubuntu/focal64"
        docker_manager.vbguest.no_remote = true
        docker_manager.vbguest.auto_update = false
        docker_manager.vm.synced_folder ".", "/vagrant", disabled: true
        docker_manager.vm.network "public_network", bridge: "enp0s31f6", ip: "192.168.1.50"
        docker_manager.vm.provider "virtualbox" do |v|     
            v.memory= 2048
            v.cpus = 2
            v.name = "docker_manager"
        end
    end
    #docker_worker_1
    config.vm.define "docker_worker_1" do |docker_worker_1|
        docker_worker_1.vm.box = "ubuntu/focal64"
        docker_worker_1.vbguest.no_remote = true
        docker_worker_1.vbguest.auto_update = false
        docker_worker_1.vm.synced_folder ".", "/vagrant", disabled: true
        docker_worker_1.vm.network "public_network", bridge: "enp0s31f6", ip: "192.168.1.51"
        docker_worker_1.vm.provider "virtualbox" do |v|     
            v.memory= 2048
            v.cpus = 2
            v.name = "docker_worker_1"
        end
    end
 #docker_worker_2
    config.vm.define "docker_worker_2" do |docker_worker_2|
        docker_worker_2.vm.box = "ubuntu/focal64"
        docker_worker_2.vbguest.no_remote = true
        docker_worker_2.vbguest.auto_update = false
        docker_worker_2.vm.synced_folder ".", "/vagrant", disabled: true
        docker_worker_2.vm.network "public_network", bridge: "enp0s31f6", ip: "192.168.1.52"
        docker_worker_2.vm.provider "virtualbox" do |v|     
            v.memory= 2048
            v.cpus = 2
            v.name = "docker_worker_2"
        end
    end
end
